# Generated by Django 5.2.7 on 2025-10-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlescope_tag_articlescope_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
